eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8080

#spring配置
spring:
  #应用配置
  application:
    #名称: OAuth2认证授权服务
    name: auth-server
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/demo_sys?serverTimezone=UTC
    username: root
    password: 239754
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #Redis
  redis:
    host: 127.0.0.1
    database: 0
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: 60
#        max-idle: 8
#        min-idle: 8
#    timeout: 10000
logging.level.org.springframework.security: DEBUG