eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8081
spring:
  application:
    name: user
security:
  oauth2:
    client:
      client-id: user
      client-secret: user123
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
      scope: select
      authorized-grant-types: password, client_credentials
